name: epicplugin
version: '${project.version}'
main: staff.main.Epicplugin
author: Not_staff
api-version: '1.17'

commands:
  epicplugin:
    description: With this command you can see all the commands of the plugin
    usage: /<command>
    aliases:
      - help

  nopvp:
    description: Command to enable/disable PvP and activates
    usage: /nopvp <on|off>
    aliases:
      - epicplugin:nopvp

  reload:
    description: Reload the config.yml configuration
    aliases:
      - reload

  repair:
    description: It is used to repair an object that is broken
    usage: /<command>
    aliases:
      - repair

  heal:
    description: with this command you can set the hearts and the food bar
    usage: /<command>
    aliases:
      - heal

permissions:
  epicplugin.reload:
    description: Reload the plugin configuration
    default: false

  epicplugin.help:
    description: With this command you can see all the commands of the plugin
    default: false

  epicplugin.nopvp:
    description: Command to enable/disable PvP and activates
    default: false

  epicplugin.repair:
    description: repair a broken object
    default: false

  epicplugin.heal:
    description: Used to heal a player
    default: false
